### ISSUE TITLE
Test for adding account fails

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1459]
The test where we add accounts often fails:
```

ot ok 210 checking setup.sh: setup.sh email add and login
# (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
#  in test file test/tests.bats, line 1015)
#   `assert_output "passdb: setup_email_add@example.com auth succeeded"' failed
# 
# -- output differs --
# expected : passdb: setup_email_add@example.com auth succeeded
# actual   : passdb: setup_email_add@example.com auth failed
# --

```

Modify the test so that it includes the mail log in the assert (assert that the log contains a matching line). Then perhaps we can find out why.

**Comment by youtous** [comment]
My last CI failed on this test. I've added two `wait_for_service` instruction in the linked PR.
It should solve the instability of this test (I hope so).

**Comment by erik-wramner** [comment]
Not so sure (but we can hope!), I've added waits here before. It is way more stable now than it used to be but it still fails sometimes. It would be nice to get the full log to pin down what is happening.

**Comment by youtous** [comment]
I can confirm this test didn't failed since https://github.com/tomav/docker-mailserver/pull/1463/commits/dff7355fa9c03111cdf841bf0662e1a026f43fd5 (6 CI successful runs, 0 failure) :angel:

**Comment by erik-wramner** [comment]
Very good, though 6 runs is not that much. I think it happens more often when the CI servers are loaded and that is hard to predict. Still, let's hope it is solved.

**Comment by youtous** [comment]
The test failed today https://travis-ci.org/github/tomav/docker-mailserver/builds/681415739
:(
https://github.com/tomav/docker-mailserver/commit/dff7355fa9c03111cdf841bf0662e1a026f43fd5 Doesn't work

**Comment by neuralp** [comment]
I am seeing the same error locally on my server if that helps at all.

**Comment by erik-wramner** [comment]
I can also reproduce locally, but not every time. It usually happens when the server is under high load.

The idea I had with this is to use https://github.com/ztombol/bats-assert#assert_line to get the full log in the output when the error happens to narrow down the root cause. I just haven't had time to fix it.

**Comment by aendeavor** [comment]
I was seeing this too. I pinned this issue.
