### ISSUE TITLE
Unable to change LDAP filter for non SASL.

### ISSUE THREAD

**Issue by Joshua-Ashton** [tomav/docker-mailserver#633]
Hello!
I am unable to change the LDAP filter to be other than "(&(?objectClass=PostfixBookMailAccount)(uniqueIdentifier=%u))".

No matter what options I put in my DockerCompose.yml I always end up with that filter being executed on my ldap. I do not have a postfixbookmailaccount and I would prefer it if I didn't have to, unless it is necessary.

I have tried 
  - SASLAUTHD_LDAP_FILTER='(&(objectClass=posixAccount)(uid=%U))'
  - LDAP_FILTER='(&(objectClass=posixAccount)(uid=%U))'
  - LDAP_QUERY_FILTER='(&(objectClass=posixAccount)(uid=%U))'
but none of them have any effect.

I am using the docker openldap also, so adding the schema would prove a bit of a mess, unless there's another way to do it?

My apologies if I am being stupid - I am fairly new to Docker.

Thanks and any advice/help is greatly appreciated.
- Josh

**Comment by alinmear** [comment]
Hello @Joshua-Ashton. This is a known Bug. Please have a look at https://github.com/tomav/docker-mailserver/issues/491#issuecomment-306296358 for a workaround/solution.

**Comment by alinmear** [comment]
I will fix this today and do a pull request!

**Comment by alinmear** [comment]
@Joshua-Ashton please try with the latest version of this container. My PR #644 has been merged and should fix this.

Note that your issue should be related to the missing DOVECOT ldap part (fixed with the PR stated above).

I placed a sample config within the README. Maybe you can take a look!

Keep in Mind to use the following variables for configuration:

* `LDAP_QUERY_FILTER_USER`
* `LDAP_QUERY_FILTER_GROUP`
* `LDAP_QUERY_FILTER_ALIAS`
* `SASLAUTHD_LDAP_FILTER`
* `DOVECOT_USER_FILTER`
* `DOVECOT_PASS_FILTER`

**Comment by alinmear** [comment]
@Joshua-Ashton ; can we close this issue. Also special character should work now. Merged #648.

**Comment by Joshua-Ashton** [comment]
Hello! 
Sorry for taking an insane amount of time to get back to you, I'm pretty blind.
Decided to give this a go today but I'm still having issues although it's probably my fault - I'm fairly new to this. I just want to use regular "posixAccount"s as people with mail and no matter what I put as the filter it doesn't like it. Maybe I'm missing something...

Thanks for your help!
 - Josh

**Comment by Joshua-Ashton** [comment]
I also noticed that the DOVECOT filters appear to be commented out in the start script in the latest build.

**Comment by alinmear** [comment]
@Joshua-Ashton can you post your compose file here please, so we can investigate what's going on.

> I also noticed that the DOVECOT filters appear to be commented out in the start script in the latest build.

I am not sure whether your are referencing the following lines or not. If so, these are only default values i was not sure, whether they would breaking things or would be useful:

https://github.com/tomav/docker-mailserver/blob/9e7959fafef48b0da620d0d04d0a547029785689/target/start-mailserver.sh#L553

**Comment by johansmitsnl** [comment]
#491 might be interesting to.

**Comment by alinmear** [comment]
Seems like there is no more information on this issue. Closing it
